version: "3.4"

services:
    python2:
        build: 
            context: ./
            dockerfile: ./Dockerfile
            target: cfgov-deployment
        image: cfgov-deployment
        environment: 
          DATABASE_URL: "postgresql://cfpb:cfpb@postgres/cfgov"
    python3:
        image: cfgov-deployment
        environment: 
          DATABASE_URL: "postgresql://cfpb:cfpb@postgres/cfgov"
