version: "3.4"
volumes:
  postgres_data:
services:
    elasticsearch:
        build:
            context: ./
            dockerfile: ./docker/elasticsearch/Dockerfile
        ports:
            - "9200:9200"
            - "9300:9300"
    postgres:
        image: postgres:10.3
        restart: always
        volumes:
          - postgres_data:/var/lib/postgresql/data/
        environment:
            POSTGRES_USER: cfpb
            POSTGRES_PASSWORD: cfpb
            POSTGRES_DB: cfgov
    python2:
        build: 
            context: ./
            dockerfile: ./Dockerfile
            target: cfgov-dev
        image: cfgov-dev
        ports:
            - "8000:8000"
        environment:
            ES_HOST: elasticsearch
            PYTHON: /usr/bin/python2
        depends_on:
            - elasticsearch
            - postgres
        stdin_open: true
        tty: true
        # see also: docker-compose.override.yml, which will be processed by default
        # https://docs.docker.com/compose/extends/#adding-and-overriding-configuration
    python3:
        image: cfgov-dev
        ports:
            - "8333:8000"
        environment:
            ES_HOST: elasticsearch
        depends_on:
            - elasticsearch
            - postgres
        stdin_open: true
        tty: true
        # see also: docker-compose.override.yml, which will be processed by default
        # https://docs.docker.com/compose/extends/#adding-and-overriding-configuration
    docs:
        build:
            context: ./
            dockerfile: ./docker/docs/Dockerfile
        ports:
            - "8888:8888"
        environment:
            LANG: en_US.utf8
            LC_ALL: en_US.utf8
        volumes:
            - ./:/src/cfgov-refresh
        entrypoint:
            - sh
            - /src/cfgov-refresh/docker/docs/entrypoint.sh
        working_dir: /src/cfgov-refresh
        stdin_open: true
        tty: true
